# Generated by Django 5.0.6 on 2024-05-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_completion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.CharField(max_length=20),
        ),
    ]
